[2023-04-09 20:01:48,920] 224 werkzeug-INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.19:5000
[2023-04-09 20:01:48,920] 224 werkzeug-INFO - [33mPress CTRL+C to quit[0m
[2023-04-09 20:03:11,217] 224 werkzeug-INFO - 127.0.0.1 - - [09/Apr/2023 20:03:11] "GET / HTTP/1.1" 200 -
[2023-04-09 20:03:12,236] 224 werkzeug-INFO - 127.0.0.1 - - [09/Apr/2023 20:03:12] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-04-09 20:03:59,249] 224 werkzeug-INFO - 127.0.0.1 - - [09/Apr/2023 20:03:59] "GET /predictdata HTTP/1.1" 200 -
[2023-04-09 20:05:12,991] 1744 app-ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "/home/jarvis/coding/end_to_end_project/src/pipeline/predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jarvis/coding/end_to_end_project/venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jarvis/coding/end_to_end_project/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jarvis/coding/end_to_end_project/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jarvis/coding/end_to_end_project/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 37, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "/home/jarvis/coding/end_to_end_project/src/pipeline/predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [/home/jarvis/coding/end_to_end_project/src/pipeline/predict_pipeline.py] line number [13] error message [name 'os' is not defined]
[2023-04-09 20:05:13,000] 224 werkzeug-INFO - 127.0.0.1 - - [09/Apr/2023 20:05:13] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
